### ISSUE TITLE
Another Wikipedia app

### ISSUE THREAD

**Issue by strukturart** [wikimedia/wikipedia-kaios#3]
Hello, I also wrote a Wikipedia app for KaiOS, but it should not appear in the store. Okay for you?
https://github.com/strukturart/wikipedia-search

**Comment by stephanebisson** [comment]
Hi, you are free to create an app using the Wikipedia data. However, I'm not sure about the use of the trademark. You may read https://foundation.wikimedia.org/wiki/Trademark_policy or email trademarks@wikimedia.org for confirmation.

We always welcome volunteer developers. If you want to work with us on this app, send me a note (sbisson@wikimedia.org) and we can discuss how that can work.

Cheers

**Comment by strukturart** [comment]
@stephanebisson in my app, the user can select the language, I am looking for a json file that contains all available languages of wikipedia. Do you know where to find one?

**Comment by hueitan** [comment]
Unfortunately, I can't find the json file for all available language, you can find all the language supported in wikipedia here

- https://meta.wikimedia.org/wiki/List_of_Wikipedias
- https://en.wikipedia.org/wiki/List_of_Wikipedias

**Comment by Nikerabbit** [comment]
Would https://www.mediawiki.org/wiki/Special:ApiSandbox#action=sitematrix&format=json&smtype=language help?

**Comment by strukturart** [comment]
thank you @Nikerabbit @hueitan  I have created a gist
https://gist.github.com/strukturart/414390310a568868a8be0216c6a6b5c9

**Comment by strukturart** [comment]
I would have some questions about the use of wikipedia api, there is a forum ?

**Comment by stephanebisson** [comment]
https://www.mediawiki.org/ is where you'll find the best documentation. You can ask on the [support desk](https://www.mediawiki.org/wiki/Project:Support_desk) if you don't find what you are looking for.

**Comment by strukturart** [comment]
My app is ready, if you like you can test it, it's probably a super super  light version compared to yours ;-)
If you are looking for tester there is a very active kaiOs discord channel ...

https://github.com/strukturart/wikipedia-search
