### ISSUE TITLE
autoscroll feature

### ISSUE THREAD

**Issue by strukturart** [wikimedia/wikipedia-kaios#37]
I'am a KaiOs user....... in some apps it is helpfull to have an autoscroll function: 
https://github.com/strukturart/rss-reader/blob/dee594ace09931bba9c20f15749cc65717eb79a4/application/assets/js/script.js#L306

**Comment by stephanebisson** [comment]
Could you clarify the purpose of this issue?

If you are proposing that we add an auto-scroll feature in the app, please specify on which screen(s) and how it would work in details and we'll consider it with the team. 

Thanks

**Comment by strukturart** [comment]
If you want to read a long text it is helpful that you don't always have to press cursor down to scroll because the screen is usually very small. e.g .: the autoscroll function could be started by longpress cursor down.

**Comment by stephanebisson** [comment]
We don't really use scrolling in this app. We paginate article content like you would see with a ebook reader.
