### ISSUE TITLE
Release a build? 

### ISSUE THREAD

**Issue by foxnoodles** [wikimedia/wikipedia-kaios#86]
Would be nice to have a final working build (in releases tab). Not all us are into compiling stuff : ) 

Thanks in advance

**Comment by stephanebisson** [comment]
This application is under development and is still experimental. We don't recommend anyone to use it. When ready, it should be published in official app store(s).

**Comment by saper** [comment]
There is also an unofficial app collection at https://sites.google.com/view/b-hackers-store

**Comment by stephanebisson** [comment]
We prefer not to participate in the unofficial app collections for now. We hope to offer our app in the official stores shortly.
